version: "3.9"
services:
  ovpn:
    container_name: ovpn
    privileged: true
    cap_add:
     - NET_ADMIN
    image: darathor/openvpn
    ports:
      - "1194:1194/udp"
    environment:
      - DEBUGG=1
    volumes:
      - ./volumes/openvpn:/etc/openvpn
    networks:
      - host

networks:
  host: