version: '3.3'
services:
  dns:
    image: sameersbn/bind
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 10000
        published: 10000
        mode: host
    volumes:
      - ./stack/bind/:/data/bind/etc/
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      ROOT_PASSWORD: verysecurepassword
    networks:
      - outside
  dhcp:
    image: networkboot/dhcpd
    ports:
      - target: 67
        published: 67
        protocol: tcp
        mode: host
      - target: 68
        published: 68
        protocol: tcp
        mode: host
    volumes:
      - ./stack/isc:/data
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - outside
  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./stack/nginx/conf/conf.d/web11.conf:/etc/nginx/conf.d/web11.conf:ro
      - ./stack/nginx/conf/conf.d/web22.conf:/etc/nginx/conf.d/web22.conf:ro
      - ./stack/nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./stack/nginx/www:/var/www:ro
      - ./stack/cert_ssl:/shared/ssl
      - ./stack/users/passwd:/shared/users/passwd
      - ./stack/users/groups:/shared/users/groups
      - logs:/logs:rw
    deploy:
      restart_policy:
        condition: on-failure

networks:
  outside:
    external:
      name: "host"
volumes:
  logs: