version: '3.3'
services:
  dns:
    image: sameersbn/bind
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
    volumes:
      - ./stack/bind/:/data/bind/etc/
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      ROOT_PASSWORD: verysecurepassword
    networks:
      - outside
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
  dhcp:
    image: networkboot/dhcpd
    ports:
      - target: 67
        published: 67
        protocol: tcp
        mode: host
      - target: 68
        published: 68
        protocol: tcp
        mode: host
    volumes:
      - ./stack/isc:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - outside
networks:
  outside:
    external:
      name: "host"
volumes:
  logs: