version: "3.3"
services:
  openfire:
    container_name: openfire
    image:  sameersbn/openfire:3.10.3-19
    ports:
      - "9090:9090"
      - "5222:5222"
      - "7777:7777"
    volumes:
      - ./stack/openfire:/var/lib/openfire
networks:
  outside:
    external:
      name: "host"