version: '3.7'
services:
  dns:
    image: sameersbn/bind:latest
#    container_name: bind
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 1000
        published: 1000
        mode: host
    volumes:
      - ./stack/bind/:/data/bind/etc/
#      - ./config/bind/OFA.itb:/data/bind/etc/OFA.itb
#      - ./config/bind/named.conf.local:/data/bind/etc/named.conf.local
#      - ./config/bind/db.6.10.10:/data/bind/etc/db.6.10.10
    deploy:
#      mode: replicated
#      replicas: 1
#      update_config:
#        parallelism: 1
#        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
        - outside
  dhcp:
    image: networkboot/dhcpd:latest
#    container_name: isc
    ports:
      - target: 67
        published: 67
        protocol: tcp
        mode: host
      - target: 68
        published: 68
        protocol: tcp
        mode: host
    volumes:
      - ./stack/isc:/data
#      - ./config/isc/dhcpd.conf:/data/dhcpd.conf:ro
    deploy:
#      mode: replicated
#      replicas: 1
#      update_config:
#        parallelism: 1
#        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
        - outside
  nginx:
    image: nginx:latest
#    container_name: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
#      - target: 81
#        published: 81
#        protocol: tcp
#        mode: host
#  environment:
#   - NGINX_HOST=web11.ofa.itb
#   - NGINX_PORT=80
    volumes:
#      - ./stack/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./stack/nginx/conf/conf.d/web11.conf:/etc/nginx/conf.d/web11.conf:ro
      - ./stack/nginx/conf/conf.d/web22.conf:/etc/nginx/conf.d/web22.conf:ro
      - ./stack/nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./stack/nginx/conf/conf.d/redirect.conf:/etc/nginx/conf.d/redirect.conf
      - ./stack/nginx/www:/var/www:ro
      - ./stack/cert_ssl:/shared/ssl
      - ./stack/users/passwd:/shared/users/passwd
      - ./stack/users/groups:/shared/users/groups
  sftp-web:
    image: atmoz/sftp
# https://hub.docker.com/r/atmoz/sftp
    ports:
      - target: 22
        published: 23
        protocol: tcp
        mode: host
    volumes:
      - ./stack/nginx/www:/home/test:rw
      - ./stack/key_ssh/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key:ro
      - ./stack/key_ssh/ssh_host_ecdsa_key.pub:/etc/ssh/ssh_host_ecdsa_key.pub:ro
      - ./stack/key_ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./stack/key_ssh/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro
      - ./stack/key_ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./stack/key_ssh/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:ro
    command: profe:chequejant
networks:
  outside:
    external:
      name: "host"
