version: "3"
services:
  ovpn:
    container_name: ovpn
#    cap_add:
#     - NET_ADMIN
    image: kylemanna/openvpn
    ports:
      - "1194:1194/udp"
    environment:
      - DEBUGG=1 # FOR TESTING PORPOUSES
    volumes:
      - ovpn:/etc/openvpn
    networks:
      - host
networks:
  host:
volumes:
  ovpn:
