version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
       - ./stack/shared:/samba_shared/shared
       - ./stack/files:/samba_shared/files
       - ./stack/samba/smb.conf:/etc/samba/smb.conf:ro
#       - ./stack/users:/samba_shared/files
#    environment:
#      SHARE: '/samba_shared/'
#       INCLUDE: "/samba_config/smb.conf"
#    volumes:
#      - /mnt:/mnt:z
#      - /mnt2:/mnt2:z
#    command: '-s "Mount;/mnt" -s "Bobs Volume;/mnt2;yes;no;no;bob" -u "bob;bobspasswd" -p'

networks:
  default:
