version: "3.3"
services:
  postfix_srv:
    container_name: postfix
    image: classcat/postfix-dovecot
    ports:
      - "2022:22"
      - "25:25"
      - "110:110"
      - "143:143"
    environment:
      TZ: "Europe/Madrid"
      ROOT_PASSWORD: mypassword
      HOSTNAME: carter.ofa.itb
      DOMAINNAME: ofa.itb
      USERS: alumne:a,a:a,b:b,profe:chequejant,motioneye_backups:a
    volumes:
      - "./stack/nginx/www/web11/html/privatefolder/logs/postfix/emails:/var/mail:rw"
      - "./stack/nginx/www/web11/html/privatefolder/logs/postfix/mail.log:/var/log/mail.log:rw"
      - "./stack/nginx/www/web11/html/privatefolder/logs/postfix/mail.err:/var/log/mail.err:rw"
      - "./stack/nginx/www/web11/html/privatefolder/logs/postfix/spamassasin:/var/log/spamassasin:rw"
      - "./stack/nginx/www/web11/html/privatefolder/logs/postfix/supervisor:/var/log/supervisor:rw"
    command: ["/bin/sh", "-c", "/opt/cc-init.sh; /usr/sbin/addgroup  alumne mail && \
                   /usr/sbin/addgroup profe mail && \
                   /usr/sbin/addgroup a mail && \
                   /usr/sbin/addgroup b mail && \
                   /usr/sbin/addgroup motioneye_backups mail && \
                   /usr/bin/touch /var/mail/a /var/mail/b /var/mail/alumne /var/mail/profe /var/mail/motioneye_backups && \
                   /bin/chmod 777 /var/log/mail.log /var/log/mail.err /var/mail -R && \
                   /bin/chown a:mail /var/mail/a && \
                   /bin/chown b:mail /var/mail/b && \
                   /bin/chown alumne:mail /var/mail/alumne && \
                   /bin/chown profe:mail /var/mail/profe && \
                   /bin/chown motioneye_backups:mail /var/mail/motioneye_backups && \
                   /usr/bin/supervisord -c /etc/supervisor/supervisord.conf"]
networks:
  outside:
    external:
      name: "host"
