version: "3.3"
services:
  dhcp:
#    image: "swarm_dhcp"
#    image: docker-dhcp
    build:
        context: .
        dockerfile: docker-dhcp
    ports:
      - target: 67
        published: 67
        protocol: tcp
        mode: host
      - target: 68
        published: 68
        protocol: tcp
        mode: host
#      - "68:68/udp"
#      - "67:67/udp"
#    volumes:
#      - ./config:/config
#      - ./test:/tmp
#    network_mode: "outside"
#    restart: unless-stopped
  dns:
#    image: "swarm_dns"
#    image: docker-dns
    build:
        context: .
        dockerfile: docker-dns
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 1000
        published: 1000
        mode: host
    volumes:
       - ./bind:/data/bind/etc
#    network_mode: "outside"
#    restart: unless-stopped
#networks:
#  outside:
#    external:
#      name: "host"
