version: '3.3'
services:
  dns:
    image: sameersbn/bind:latest
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 1000
        published: 1000
        mode: host
    volumes:
      - ./bind:/data/bind/etc
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
        - outside
  dhcp:
    image: networkboot/dhcpd:latest
    ports:
      - target: 67
        published: 67
        protocol: tcp
        mode: host
      - target: 68
        published: 68
        protocol: tcp
        mode: host
    volumes:
      - ./dhcp:/data
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
        - outside
networks:
  outside:
    external:
      name: "host"
